# Automatically generated by configure - do not modify
prefix=
MAKE=make
CC=gcc
GCC_MAJOR=3
HOST_CC=gcc
AR=ar
STRIP=strip -s -R .comment -R .note
CFLAGS=-O2
LDFLAGS=
EXTRALIBS=-lm
VERSION=0.3.3
CONFIG_NETWORK=yes
CONFIG_WIN32=yes
SRC_PATH=
